apiVersion: v1
kind: Service
metadata:
  name: hydra-cluster-ip-service
spec:
  type: ClusterIP
  selector:
      component: hydra
  ports:
    - port: 4444
      targetPort: 4444
      name: public-port
    - port: 4445
      targetPort: 4445
      name: admin-port
    - port: 5555
      targetPort: 5555
      name: token-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hydra
  template:
    metadata:
      labels:
        component: hydra
    spec:
      containers:
        - name: hydra
          image: oryd/hydra:v1.4.2
          ports:
            - containerPort: 4444
            - containerPort: 4445
            - containerPort: 5555
          command:
            - "hydra"
            - "serve"
            - "all"
            - "--dangerous-force-http"
          env:
            - name: DSN
              value: postgres://hydra:abc123@postgres-cluster-ip-service:5432/hydra?sslmode=disable
            - name: OAUTH2_EXPOSE_INTERNAL_ERRORS
              value: "true"
            - name: OIDC_SUBJECT_IDENTIFIERS_ENABLED
              value: "true"
            - name: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
              value: youReallyNeedToChangeThis
            - name: SECRETS_SYSTEM
              value: youReallyNeedToChangeThis
            - name: SERVE_PUBLIC_CORS_ALLOWED_ORIGINS
              value: /
            - name: SERVE_PUBLIC_CORS_ENABLED
              value: "true"
            - name: URLS_CONSENT
              value: /identity/consent
            - name: URLS_ERROR
              value: /identity/account/oauth-error
            - name: URLS_LOGIN
              value: /identity/login
            - name: URLS_LOGOUT
              value: /identity/logout
            - name:  URLS_SELF_ISSUER
              value: /auth