apiVersion: v1
kind: Service
metadata:
 name: reaction-server-cluster-ip-service
spec:
 type: ClusterIP
 selector:
   component: reaction-server
 ports:
   - port: 3000
     targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: reaction-server-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     component: reaction-server
 template:
   metadata:
     labels:
       component: reaction-server
   spec:
     containers:
       - name: reaction-server
         image: kraiymbek/reaction-server:v1
         ports:
           - containerPort: 3000
         env:
           - name: MONGO_URL
             value: mongodb://reaction_user:abc123@mongod-0.mongodb-service,mongod-1.mongodb-service,mongod-2.mongodb-service:27017/reaction
           - name: ROOT_URL
             value: /api
           - name: STRIPE_API_KEY
             value: YOUR_PRIVATE_STRIPE_API_KEY